repos:
  - repo: local
    hooks:
      - id: vp-fmt
        name: vp fmt
        entry: vp fmt
        language: system
        pass_filenames: false

      - id: vp-lint
        name: vp lint
        entry: vp lint
        language: system
        pass_filenames: false

      - id: vp-test
        name: vp test
        entry: vp test --run
        language: system
        pass_filenames: false
